# Faster RCNN model 

In [1]:
%load_ext autoreload
%autoreload 2
import os
import torch as t
from torch import nn
from utils.config import opt
from model import FasterRCNNVGG16,FasterRCNNVGG16Extractor
from trainer import FasterRCNNTrainer
from data.util import  read_image
from utils.vis_tool import vis_bbox
from utils import array_tool as at
%matplotlib inline

C:\Users\Administrator\Desktop\rcnn lstm\model\utils\nms\non_maximum_suppression.py:12: UserWarning: 
    the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code: 
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')


In [2]:
t.FloatTensor([[1,2]])

tensor([[1., 2.]])

In [3]:
faster_rcnn = FasterRCNNVGG16()
trainer = FasterRCNNTrainer(faster_rcnn).cuda()

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "G:\Anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "G:\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "G:\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "G:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "G:\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "G:\Anaconda3\lib\http\client.py

In [4]:
trainer.load('G:\\models\\fasterrcnn_torchvision_pretrain.pth')
opt.caffe_pretrain=False # this model was trained from torchvision-pretrained model

In [5]:
img = read_image('misc/COCO_train2014_000000000036.jpg')
img = t.from_numpy(img)[None]
img = at.totensor(img).float()

In [6]:
img.shape

torch.Size([1, 3, 640, 481])

In [7]:
pool,roi_cls_locs, roi_scores, rpn_locs, rpn_scores, rois, anchors, scales,_ = faster_extractor.extract(img,35)

# Word Embedding

In [8]:
from gensim.models import Word2Vec
import nltk

In [9]:
embedding_file = 'G:/data/coco_filtered_word2vec_1024'

In [10]:
word_embedding = Word2Vec.load(embedding_file)

# coco dataset

In [11]:
from pycocotools.coco import COCO

In [12]:
english_punctuations = [',', '.', ':', ';', '?', '(', ')', '[', ']', '&', '!', '*', '@', '#', '$', '%','-']
filter_word = english_punctuations + nltk.corpus.stopwords.words('english')

In [13]:
dataType = 'train2017'
annDir = 'G:/data/coco/annotations'
ann_caption_file = '{}/captions_{}.json'.format(annDir, dataType)
ann_instance_file = '{}/instances_{}.json'.format(annDir, dataType)

In [14]:
coco_caption=COCO(ann_caption_file)
coco_instance = COCO(ann_instance_file)

loading annotations into memory...
Done (t=2.11s)
creating index...
index created!
loading annotations into memory...
Done (t=29.57s)
creating index...
index created!


In [15]:
img_ids  = coco_caption.getImgIds()

In [16]:
annid = coco_caption.getAnnIds(img_ids[0:2])
instance_id = coco_instance.getAnnIds(img_ids[0])
print(annid)

[770337, 771687, 772707, 776154, 781998, 681330, 686718, 688839, 693159, 693204]


In [17]:
coco_caption.loadImgs(img_ids[0])

[{'license': 3,
  'file_name': '000000391895.jpg',
  'coco_url': 'http://images.cocodataset.org/train2017/000000391895.jpg',
  'height': 360,
  'width': 640,
  'date_captured': '2013-11-14 11:18:45',
  'flickr_url': 'http://farm9.staticflickr.com/8186/8119368305_4e622c8349_z.jpg',
  'id': 391895}]

In [18]:
coco_caption.loadAnns(annid)

[{'image_id': 391895,
  'id': 770337,
  'caption': 'A man with a red helmet on a small moped on a dirt road. '},
 {'image_id': 391895,
  'id': 771687,
  'caption': 'Man riding a motor bike on a dirt road on the countryside.'},
 {'image_id': 391895,
  'id': 772707,
  'caption': 'A man riding on the back of a motorcycle.'},
 {'image_id': 391895,
  'id': 776154,
  'caption': 'A dirt path with a young person on a motor bike rests to the foreground of a verdant area with a bridge and a background of cloud-wreathed mountains. '},
 {'image_id': 391895,
  'id': 781998,
  'caption': 'A man in a red shirt and a red hat is on a motorcycle on a hill side.'},
 {'image_id': 522418,
  'id': 681330,
  'caption': 'A woman wearing a net on her head cutting a cake. '},
 {'image_id': 522418,
  'id': 686718,
  'caption': 'A woman cutting a large white sheet cake.'},
 {'image_id': 522418,
  'id': 688839,
  'caption': 'A woman wearing a hair net cutting a large sheet cake.'},
 {'image_id': 522418,
  'id': 69

In [19]:
coco_instance.loadAnns(instance_id)

[{'segmentation': [[376.97,
    176.91,
    398.81,
    176.91,
    396.38,
    147.78,
    447.35,
    146.17,
    448.16,
    172.05,
    448.16,
    178.53,
    464.34,
    186.62,
    464.34,
    192.28,
    448.97,
    195.51,
    447.35,
    235.96,
    441.69,
    258.62,
    454.63,
    268.32,
    462.72,
    276.41,
    471.62,
    290.98,
    456.25,
    298.26,
    439.26,
    292.59,
    431.98,
    308.77,
    442.49,
    313.63,
    436.02,
    316.86,
    429.55,
    322.53,
    419.84,
    354.89,
    402.04,
    359.74,
    401.24,
    312.82,
    370.49,
    303.92,
    391.53,
    299.87,
    391.53,
    280.46,
    385.06,
    278.84,
    381.01,
    278.84,
    359.17,
    269.13,
    373.73,
    261.85,
    374.54,
    256.19,
    378.58,
    231.11,
    383.44,
    205.22,
    385.87,
    192.28,
    373.73,
    184.19]],
  'area': 12190.44565,
  'iscrowd': 0,
  'image_id': 391895,
  'bbox': [359.17, 146.17, 112.45, 213.57],
  'category_id': 4,
  'id': 151091},


In [20]:
word_embedding.wv.vector_size

1024

In [21]:
corpus =[[word for word in nltk.tokenize.word_tokenize(ann['caption'].lower()) if word not in filter_word] for ann in coco_caption.loadAnns(annid)]      

In [22]:
print(corpus)

[['man', 'red', 'helmet', 'small', 'moped', 'dirt', 'road'], ['man', 'riding', 'motor', 'bike', 'dirt', 'road', 'countryside'], ['man', 'riding', 'back', 'motorcycle'], ['dirt', 'path', 'young', 'person', 'motor', 'bike', 'rests', 'foreground', 'verdant', 'area', 'bridge', 'background', 'cloud-wreathed', 'mountains'], ['man', 'red', 'shirt', 'red', 'hat', 'motorcycle', 'hill', 'side'], ['woman', 'wearing', 'net', 'head', 'cutting', 'cake'], ['woman', 'cutting', 'large', 'white', 'sheet', 'cake'], ['woman', 'wearing', 'hair', 'net', 'cutting', 'large', 'sheet', 'cake'], ['woman', 'cutting', 'white', 'cake'], ['woman', 'marking', 'cake', 'back', 'chef', "'s", 'knife']]


In [23]:
corpus_vectors = [t.from_numpy(np.array([word_embedding[word] for word in sentence if word in word_embedding.wv.vocab]))  for sentence in corpus]

G:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


In [24]:
batch_in = t.zeros((5,35,1024))
for i in range(5):
    batch_in[i,:corpus_vectors[i].shape[0],:] = corpus_vectors[i]

# lstm 

In [25]:
lstm = nn.LSTM(input_size=1024,hidden_size=512,batch_first=True)
out,_ = lstm(batch_in)

In [26]:
out.shape

torch.Size([5, 35, 512])

In [27]:
predict = t.FloatTensor([[1,0.5,0],[0.5,0.7,1]])
label = t.FloatTensor([[1,1,0],[1,1,1]])

In [28]:
bce = nn.BCELoss()

In [29]:
bce(predict,label)

tensor(0.2905)

In [30]:
sim_mat = t.matmul(pool.squeeze(),out[0].t())

In [31]:
sim_mat_flat =  t.flatten(sim_mat)

In [34]:
k = 30

In [43]:
kth,_ = t.kthvalue(sim_mat_flat,len(sim_mat_flat)-30)

In [47]:
idx_k = sim_mat > kth

In [79]:
m_idx = (t.sum(idx_k,1)>0).float()

In [78]:
n_idx = (t.sum(idx_k,0) > 0).float()

In [54]:
cons_feature_shape = (k,lstm.hidden_size)

In [80]:
m_idx

tensor([0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.])

In [84]:
m_idx.view(-1,1).repeat(1,lstm.hidden_size)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [82]:
cons_image = pool.squeeze() * m_idx.view(-1,1).repeat(1,lstm.hidden_size)

In [85]:
pool.squeeze()

tensor([[0.0000, 0.5296, 0.3276,  ..., 0.2113, 0.0000, 0.0000],
        [0.0000, 0.4907, 0.3005,  ..., 0.0655, 0.0000, 0.0000],
        [0.0000, 0.3859, 0.5170,  ..., 0.3728, 0.0000, 0.0000],
        ...,
        [0.0000, 0.1540, 0.3035,  ..., 0.1910, 0.0000, 0.0000],
        [0.0000, 0.3943, 0.5780,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0037,  ..., 0.0017, 0.0000, 0.0000]],
       grad_fn=<SqueezeBackward0>)

In [83]:
cons_image

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.4907, 0.3005,  ..., 0.0655, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.3943, 0.5780,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)

In [86]:
cons_text = out[0] * n_idx.view(-1,1).repeat(1,lstm.hidden_size)

In [87]:
cons_text

tensor([[ 0.0377,  0.0041, -0.0319,  ..., -0.1250,  0.0064,  0.1792],
        [ 0.0000, -0.0000, -0.0000,  ..., -0.0000,  0.0000,  0.0000],
        [-0.0975,  0.0493, -0.0754,  ..., -0.0980,  0.0840,  0.1042],
        ...,
        [-0.0000,  0.0000, -0.0000,  ..., -0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000, -0.0000,  ..., -0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000, -0.0000,  ..., -0.0000, -0.0000,  0.0000]],
       grad_fn=<MulBackward0>)